services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
    command: ["-jar", "-Dspring.profiles.active=postgres", "/app.jar"]
  db:
    image: postgres:17.1
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    ports:
      - 5432:5432
volumes:
  db-data:
